### ISSUE TITLE
Update to the latest code

### ISSUE THREAD

**Issue by pckujawa** [fwenzel/pdftk#1]
http://pdftk.sourcearchive.com/ has it, for example. This repo shows up in the first page of google results, and pdftk doesn't update very often, so it'd be a really nice contribution to the community to update this mirror. Thanks!

**Comment by fwenzel** [comment]
Thanks for the hint, and sorry I did not see this message until now. I'll take a look!

**Comment by fwenzel** [comment]
https://github.com/fwenzel/pdftk/commit/a3db40d1a43207eaad558aa9591ef81403b51616

Hope this helps!
